### ISSUE TITLE
Next.jsをVercelにデプロイ

### ISSUE THREAD

**Issue by geyageya** [london-newyork/Qin_Todo_J2#22]
## 概要

・今回準備したNext.jsのファイルを、Vercelにデプロイする。
・シマブーさんは、Next.jsの動画で毎回、Vercelにデプロイされていたので、それに習う

参考画像：https://qin.salon/archives/flAGDWuuTckIShSsLHNq

## タスク

- [x] Vercelのアカウントを作る
- [x] GitHubと連携させる
- [x] GitHubにアップすると、自動的にVercelにデプロイするよう、Vercel設定する
- [x] デプロイする

**Comment by geyageya** [comment]
forkしてVercelへデプロイしました https://qin-todo-j2.vercel.app/

**Comment by london-newyork** [comment]
ありがとうございます！

**Comment by geyageya** [comment]
デプロイできたので、Closeします。
