### ISSUE TITLE
【 UI 】ラジオボタン及びタスク入力欄の作成 

### ISSUE THREAD

**Issue by yamataso** [london-newyork/Qin_Todo_J2#23]
## 概要

タスク入力欄の作成をよろしくお願いします。
（ラジオボタンは除く）

## 画像 / URL

・アプリ
<img width="415" alt="スクリーンショット 2022-02-19 20 07 30" src="https://user-images.githubusercontent.com/87214030/154798916-43cbd793-0314-479f-bff9-db19f52aef19.png">

・PC
<img width="913" alt="スクリーンショット 2022-02-19 20 15 27" src="https://user-images.githubusercontent.com/87214030/154798938-a6ffc350-b24f-413e-b8ab-532e04853ea9.png">

※実装時は、キャプチャ画像より、実際の Figma を参考にしてご作成ください。

## Figma URL

・アプリ
https://www.figma.com/file/SNPCXNu0V6k6wHS4piYyS2/Qin-Todo?node-id=41%3A1709

・PC
https://www.figma.com/file/SNPCXNu0V6k6wHS4piYyS2/Qin-Todo?node-id=2234%3A2673

## タスク

- [ ] タスク入力欄を作成

**Comment by london-newyork** [comment]
機能の方で作成しているためクローズ

**Comment by london-newyork** [comment]
#48
